- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "/home/pwilliams/.ssh/id_ed25519"
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
  tasks:
    - include_tasks: ./tasks/zsh.yml
    - include_tasks: ./tasks/dotfiles.yml
    - include_tasks: ./tasks/ssh.yml
    - include_tasks: ./tasks/network.yml
    - include_tasks: ./tasks/go.yml
    - include_tasks: ./tasks/node.yml
    - include_tasks: ./tasks/dotfiles.yml
