- name: download go
  shell: wget https://go.dev/dl/go1.22.2.linux-amd64.tar.gz
  tags:
    - go
- name: install go
  shell: rm -rf /usr/local/go && tar -C /usr/local -xzf go1.22.2.linux-amd64.tar.gz
  tags:
    - go
- name: add go to path
  shell: export PATH=$PATH:/usr/local/go/bin
  tags:
    - go
- name: add go bin
  shell: export GOROOT=/usr/local/go
  tags:
    - go
